pipeline {
    agent any
 tools {
        maven 'M3'
        jdk 'jdk'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Git Init') {
        steps{
            sh 'git init'
            }
        }
        stage('SCM Fetch From sc-staging') {
        steps{
            git branch: 'sc-staging', url: 'https://github.com/Kishanrampure/DevOps-Boardgame-Project.git'
            }
        }
        stage('Maven Compile') {
        steps {
                sh 'mvn clean compile'
            }
        }
        stage('Unit Test'){
        steps {
                sh 'mvn test'
            }
        }
	stage('Integration Test'){
        steps {
                sh 'mvn verify -DskipUnitTests'
            }
        }
        stage ('Code Analysis With CheckStyle'){
        steps {
                sh 'mvn checkstyle:checkstyle'
            }
            post {
                success {
                    echo 'Generated Analysis Result'
                }
            }
        }
        stage("OWASP Dependency Check"){
        steps{
                dependencyCheck additionalArguments: '--scan ./ --format HTML ', odcInstallation: 'OWASP'
                dependencyCheckPublisher pattern: '**/dependency-check-report.html'
            }
        }
        stage('Trivy FS Check CI') {
        steps {
                sh "trivy fs ."
            }
        }
        stage('SonarQube Analysis') {
            environment {
             SCANNER_HOME = tool 'sonar-scanner'
          }
        steps{
                withSonarQubeEnv('sonarserver') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Boardgame \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=Boardgame '''

                }
            }
        }
        stage('Git Push to deployment') {
	    environment {
                commitmsg = "'CodeChange'"
            }
        steps {
	       script{
                   withCredentials([
                    gitUsernamePassword(credentialsId: 'mygitid', gitToolName: 'Default')
                    ] ) {
                    sh '''
                    git add .
		    git remote -v
                    git status
		    git commit -a -m ${commitmsg}
                    git branch -M deployment
                    git push -u origin deployment --force
                    '''
                 }
	          }
          }
      }

        stage('Git Init') {
        steps{
            sh 'git init'
            }
        }
        stage('SCM Fetch') {
        steps{
            git branch: 'deployment', url: 'https://github.com/Kishanrampure/DevOps-Boardgame-Project.git'
            }
        }
        stage('Maven Install'){
        steps{
              sh "mvn clean install"
             }
        }
         stage('Docker Build') {
          steps {
                sh 'chmod +x mvnw'
                sh 'chmod +x ./mvnw'
                sh 'sudo chmod 777 /var/run/docker.sock'
                sh 'docker build -t us-west1-docker.pkg.dev/<Project-ID>/boardgame/boardgame:latest .'
            }
        }
        stage('Docker Image Test'){
        steps {
                sh 'trivy image us-west1-docker.pkg.dev/<Project-ID>/boardgame/boardgame:latest'
            }
        }
        stage('Trivy FS Check') {
        steps {
                sh "trivy fs ."
            }
        }
        stage('Authenticate to GCR') {
        steps {
                sh "sudo gcloud auth configure-docker us-west1-docker.pkg.dev"
              }
         }
        stage('Push image to Artifact Registry') {
        steps {
             sh "sudo docker push us-west1-docker.pkg.dev/<Project-ID>/boardgame/boardgame:latest"
        }
      }
      stage('Setup Connection GKE cluster') {
      steps {
              sh "gcloud container clusters get-credentials boardgame --zone us-west1-a --project <Project-ID>"
          }
      }
      stage('Create Deployment') {
      steps {
             sh "kubectl apply -f deploy.yml"
             }
      }
      stage('Status of Deployment') {
      steps {
             sh "kubectl get deploy"
             }
      }
      stage('Create Load Balancer Service') {
      steps {
             sh "kubectl apply -f service.yml"
             }
      }
      stage('Status of Service') {
      steps {
             sh "kubectl get svc"
             }
      }
        stage('Git Push to GCP') {
	  environment {
                commitmsg = "'codeChangesSC'"
            }
        steps {
	       script{
                   withCredentials([
                    gitUsernamePassword(credentialsId: 'mygitid', gitToolName: 'Default')
                    ] ) {
                    sh '''
                    git add .
                    git branch -M GCP
		            git remote -v
                    git status
		            git commit -a -m ${commitmsg}
                    git push -u origin GCP --force
                    '''
                  }
	           }
            }
        }

    }
}

